[features]
seeds = false
skip-lint = false

[programs.localnet]
idle_game = "HMz4pAww1UAhwnsE2WFEkSTazKgFf5pwUAnnMxvDbrjf"
[programs.devnet]
idle_game = "HMz4pAww1UAhwnsE2WFEkSTazKgFf5pwUAnnMxvDbrjf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/jonasmac2/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
