[features]
seeds = false
[programs.localnet]
seven_seas = "BZdtLcjPeNCC65Y71Qo5Xhbtf1udCR6fBiPyk91x554M"
[programs.devnet]
seven_seas = "BZdtLcjPeNCC65Y71Qo5Xhbtf1udCR6fBiPyk91x554M"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/jonasmac2/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
