[features]
seeds = false
[programs.localnet]
seven_seas = "HgmkLCs9Ti1e3juimSR8JNhdLE6eup5Pjk6PujiewZU6"
[programs.devnet]
seven_seas = "HgmkLCs9Ti1e3juimSR8JNhdLE6eup5Pjk6PujiewZU6"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/jonasmac2/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
